name: Grundlagen_Python
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  # Jupyter notebook, -lab, and plugins
  - jupyter
  - jupyterlab
  # Scientific stack
  - numpy
  - matplotlib
  - pandas
  - scipy
  # grading and testing
  - pytest
  - hypothesis
  # packages from pypi
  - pip
  - pip:
    - statsmodels
    - jupyterquiz
    - nbgrader
    - https://gitlab.ub.uni-giessen.de/hpc-core-facility/teaching-infrastructure/pytest-nbgrader/-/archive/master/pytest-nbgrader-master.zip

variables:
  COURSE_TITLE: 'Grundlagen der Programmierung mit Python (07-BDS-04)'
